version: '3.6'

services:
  pm2:
    container_name: ddev-${DDEV_SITENAME}-pm2
    image: keymetrics/pm2:8-alpine
    ports:
      - 80
    links:
      - web:contenta.ddev.local
    volumes:
      - ../contentajs:/app
    working_dir: /app
    # Install from the service and start.
    command: sh -c 'npm install --no-audit && npm install @contentacms/redis --no-audit && npm start'
    # Install localy or already installed, just start.
    #command: npm start
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
      com.ddev.app-url: $DDEV_URL
    environment:
      - VIRTUAL_HOST=contentajs.ddev.local
      - HTTP_EXPOSE=80:80
