version: '3.6'

services:
  pm2:
    container_name: ddev-${DDEV_SITENAME}-pm2
    image: keymetrics/pm2:latest-alpine
    ports:
      - 3000
    links:
      - web:contenta.ddev.site
    volumes:
      - ../contentajs:/home/node/app
    working_dir: /home/node/app
    user: "node"
    # Install from the service and start.
    command: sh -c 'npm config set strict-ssl false && npm install --no-audit && npm install https://github.com/contentacms/contentajsRedis/archive/master.tar.gz --no-audit && sleep 10s && npm start'
    # Install locally or already installed, just start.
    #command: npm start
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=contentajs.ddev.site
      - HTTP_EXPOSE=80:3000
